language: ruby
rvm:
- 2.2.0
cache: bundler
sudo: false
notifications:
  email: false
  hipchat:
    rooms:
      secure: bedz3d+0QX1/LEEWuprVSF66T99xzR/Ax7gyndveGYsmIeprWnbZ+yq5D8DiFLqE5hvgZ27oyn1jss/hVLxjVcAbW6dWDT+t1E63FdqemvKrHvI48hF02BGEaDU5C9wvt+EkxveEWjXju5BMM860oMhRYgkQfg1m/TfZsgujljc=
addons:
  code_climate:
    repo_token: af4490358bda5d52d6ee6f3264916d917001a76f287c38b2db3bb8f6152e2a6b
deploy:
  provider: heroku
  api_key:
    secure: BoQ2rDgQVxvgA3PzUVQaZX9W17Rgxmuy5dkiTm+J8hZBAvyj50Zs/4j2Vc2FXc1zrqoWmJ82Am1+/9Agk/y9h0iOa06XxATvIUZZ3mHfH3KBGvG3YnL2v5CaJwyxXwT+kx/wrjomyEO/pDVIHvIMiZonZEZIk6+6BVdF/pTRN5o=
  app: summitcdn
  on:
    repo: smtcs/cdn
